apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tanzu-java-app
  description: Tanzu Java Spring-Boot Web App, displaying kubernetes info on '/k8s' endpoint. Written by Guy Balmas.
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
    - kubernetes
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=tanzu-java-app'
    'backstage.io/techdocs-ref': dir:.
  links:
    - url: http://tanzu-java-app.apps.tap-guy-lab-p8m8nm3rts18.ts-cna.com
      name: Hello-World
    - url: http://tanzu-java-app.apps.tap-guy-lab-p8m8nm3rts18.ts-cna.com/k8s
      name: K8S-spec
spec:
  type: service
  lifecycle: experimental
  owner: cloud-native-applications-team
  providesApis:
    - welcome
    - k8s
